# MiWeatherLocation Native configuration
enabled=1
pos_id=23.106_113.325
name=广州塔
street_name=阅江西路
longitude=113.324521
latitude=23.106428
belongings=广州市, 广东, 中国
extra=weathercn:101280108
locale=zh_cn
